### ISSUE TITLE
Full dataset of FB15k-37

### ISSUE THREAD

**Issue by RRRRRusellllll** [honggen-zhang/HaSa-CKGE#1]
Hi~
Could you please provide access to the full FB15 dataset or guide me on how to obtain it?  If there are any specific terms or conditions for using this dataset, I would be happy to comply with them.

**Comment by honggen-zhang** [comment]
I was trying to upload the data but it too large to upload to Github. I upload the entity2name file and entity distribution file. You might can build the data yourself if you have the FB15k-237 dataset.

**Comment by RRRRRusellllll** [comment]
Thank you！
